<?php

namespace Database\Seeders;

use App\Models\Word;
use Illuminate\Database\Seeder;

class WordSeeder extends Seeder
{
    public function run(): void
    {
        $words = [
            [
                'term' => 'SELECT',
                'description' => 'テーブルからデータを取得するSQL文。取得するカラムを指定する。',
                'sql_example' => "SELECT id, name, email FROM users;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'WHERE',
                'description' => '条件を指定してデータを絞り込む句。',
                'sql_example' => "SELECT * FROM users WHERE age >= 20;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ORDER BY',
                'description' => '取得結果を指定したカラムで並び替える句。ASC（昇順）またはDESC（降順）を指定できる。',
                'sql_example' => "SELECT * FROM users ORDER BY created_at DESC;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'GROUP BY',
                'description' => '指定したカラムの値でグループ化する句。集計関数と組み合わせて使う。',
                'sql_example' => "SELECT department, COUNT(*) FROM employees GROUP BY department;",
                'section' => '集計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'HAVING',
                'description' => 'GROUP BYでグループ化した結果にさらに条件を指定する句。WHEREと違い集計関数が使える。',
                'sql_example' => "SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) >= 5;",
                'section' => '集計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INNER JOIN',
                'description' => '2つのテーブルで一致するデータだけを結合して取得するJOIN。ON句で結合条件を指定する。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nINNER JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LEFT JOIN',
                'description' => '左テーブルのすべてのレコードと、右テーブルで一致するレコードを結合する。右テーブルに一致がない場合はNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nLEFT JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DISTINCT',
                'description' => '重複する行を除いてデータを取得するキーワード。',
                'sql_example' => "SELECT DISTINCT department FROM employees;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COUNT',
                'description' => '行数を数える集計関数。COUNT(*)は全行数、COUNT(カラム名)はNULL以外の行数を返す。',
                'sql_example' => "SELECT COUNT(*) FROM users;\nSELECT COUNT(email) FROM users;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SUM',
                'description' => '指定したカラムの合計値を返す集計関数。',
                'sql_example' => "SELECT SUM(price) FROM orders;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'AVG',
                'description' => '指定したカラムの平均値を返す集計関数。',
                'sql_example' => "SELECT AVG(salary) FROM employees;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MAX',
                'description' => '指定したカラムの最大値を返す集計関数。',
                'sql_example' => "SELECT MAX(price) FROM products;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MIN',
                'description' => '指定したカラムの最小値を返す集計関数。',
                'sql_example' => "SELECT MIN(price) FROM products;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SUBQUERY',
                'description' => 'SELECT文の中に別のSELECT文を入れ子にしたもの。サブクエリとも呼ぶ。',
                'sql_example' => "SELECT name FROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'EXISTS',
                'description' => 'サブクエリが1件以上の結果を返す場合にTRUEとなる演算子。',
                'sql_example' => "SELECT name FROM customers c\nWHERE EXISTS (\n  SELECT 1 FROM orders o WHERE o.customer_id = c.id\n);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'IN',
                'description' => '指定したリストの中にカラムの値が含まれるかどうかを判定する演算子。',
                'sql_example' => "SELECT * FROM products WHERE category IN ('食品', '飲料', '日用品');",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LIKE',
                'description' => '文字列のパターンマッチングを行う演算子。%は任意の文字列、_は任意の1文字を表す。',
                'sql_example' => "SELECT * FROM users WHERE name LIKE '田%';",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NULL',
                'description' => '値が存在しないことを表す特殊な値。IS NULLまたはIS NOT NULLで判定する。=演算子では比較できない。',
                'sql_example' => "SELECT * FROM users WHERE email IS NULL;",
                'section' => 'SELECT',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CASE',
                'description' => '条件によって異なる値を返す式。プログラミングのif文に相当する。',
                'sql_example' => "SELECT name,\n  CASE\n    WHEN score >= 80 THEN '優'\n    WHEN score >= 60 THEN '良'\n    ELSE '可'\n  END AS grade\nFROM students;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'PRIMARY KEY',
                'description' => 'テーブルの各行を一意に識別するための制約。NULL不可かつ重複不可。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  name VARCHAR(100)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FOREIGN KEY',
                'description' => '他のテーブルの主キーを参照する制約。参照整合性を保つために使用する。',
                'sql_example' => "CREATE TABLE orders (\n  id INT PRIMARY KEY,\n  user_id INT,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNIQUE',
                'description' => 'カラムの値が重複しないことを保証する制約。NULLは複数許容される場合がある。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  email VARCHAR(255) UNIQUE\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NOT NULL',
                'description' => 'カラムにNULL値を許可しない制約。必ず値が入力される必要がある。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DEFAULT',
                'description' => 'カラムに値が指定されなかった場合に自動的に設定される値を定義する制約。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  status VARCHAR(20) DEFAULT 'active'\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INDEX',
                'description' => 'データの検索速度を向上させるためのデータ構造。検索・結合・ソートのパフォーマンスが改善される。',
                'sql_example' => "CREATE INDEX idx_users_email ON users(email);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'RIGHT JOIN',
                'description' => '右テーブルのすべてのレコードと、左テーブルで一致するレコードを結合する。左テーブルに一致がない場合はNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nRIGHT JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FULL OUTER JOIN',
                'description' => '左右両方のテーブルのすべてのレコードを結合する。一致しないレコードはNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nFULL OUTER JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNION',
                'description' => '2つのSELECT文の結果を縦に結合する演算子。重複行は自動的に除去される。',
                'sql_example' => "SELECT name FROM employees\nUNION\nSELECT name FROM contractors;",
                'section' => '集合演算',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNION ALL',
                'description' => '2つのSELECT文の結果を縦に結合する演算子。UNIONと違い重複行も含めてすべて返す。',
                'sql_example' => "SELECT name FROM employees\nUNION ALL\nSELECT name FROM contractors;",
                'section' => '集合演算',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INTERSECT',
                'description' => '2つのSELECT文の結果の共通部分を返す演算子。',
                'sql_example' => "SELECT name FROM employees\nINTERSECT\nSELECT name FROM managers;",
                'section' => '集合演算',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MINUS',
                'description' => '1つ目のSELECT文の結果から2つ目の結果を除いた差集合を返す演算子。',
                'sql_example' => "SELECT name FROM employees\nMINUS\nSELECT name FROM managers;",
                'section' => '集合演算',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'BETWEEN',
                'description' => '指定した範囲内の値を検索する演算子。境界値も含まれる。',
                'sql_example' => "SELECT * FROM products WHERE price BETWEEN 1000 AND 5000;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRUNCATE',
                'description' => 'テーブルの全データを削除するDDL文。DELETEと違いロールバックできない場合がある。',
                'sql_example' => "TRUNCATE TABLE logs;",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INSERT',
                'description' => 'テーブルに新しいレコードを追加するDML文。',
                'sql_example' => "INSERT INTO users (name, email) VALUES ('田中', 'tanaka@example.com');",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UPDATE',
                'description' => 'テーブルの既存レコードを更新するDML文。WHEREで条件を指定しないと全件更新される。',
                'sql_example' => "UPDATE users SET status = 'inactive' WHERE last_login < '2024-01-01';",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DELETE',
                'description' => 'テーブルからレコードを削除するDML文。WHEREで条件を指定しないと全件削除される。',
                'sql_example' => "DELETE FROM users WHERE status = 'inactive';",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CREATE TABLE',
                'description' => '新しいテーブルを作成するDDL文。カラム名・データ型・制約を定義する。',
                'sql_example' => "CREATE TABLE products (\n  id INT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL,\n  price INT DEFAULT 0\n);",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ALTER TABLE',
                'description' => '既存テーブルの構造を変更するDDL文。カラムの追加・削除・変更などができる。',
                'sql_example' => "ALTER TABLE users ADD COLUMN phone VARCHAR(20);\nALTER TABLE users DROP COLUMN phone;",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DROP TABLE',
                'description' => 'テーブルを完全に削除するDDL文。テーブル構造とデータがすべて削除される。',
                'sql_example' => "DROP TABLE temp_logs;",
                'section' => 'DDL',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COMMIT',
                'description' => 'トランザクション内の変更を確定させるTCL文。COMMITするまで変更は他のセッションから見えない。',
                'sql_example' => "BEGIN;\nUPDATE accounts SET balance = balance - 1000 WHERE id = 1;\nUPDATE accounts SET balance = balance + 1000 WHERE id = 2;\nCOMMIT;",
                'section' => 'トランザクション',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROLLBACK',
                'description' => 'トランザクション内の変更を取り消すTCL文。エラー発生時に変更をなかったことにする。',
                'sql_example' => "BEGIN;\nUPDATE accounts SET balance = balance - 1000 WHERE id = 1;\nROLLBACK;",
                'section' => 'トランザクション',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SAVEPOINT',
                'description' => 'トランザクション内に中間ポイントを設定するTCL文。SAVEPOINTまで部分的にROLLBACKできる。',
                'sql_example' => "SAVEPOINT sp1;\nUPDATE users SET status = 'vip' WHERE id = 1;\nROLLBACK TO sp1;",
                'section' => 'トランザクション',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'VIEW',
                'description' => 'SELECT文を仮想テーブルとして保存したもの。複雑なクエリを簡略化したり、アクセス制御に使用する。',
                'sql_example' => "CREATE VIEW active_users AS\nSELECT id, name, email FROM users WHERE status = 'active';",
                'section' => 'ビュー',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SEQUENCE',
                'description' => '連続した数値を自動生成するオブジェクト。主キーの自動採番に使用される。',
                'sql_example' => "CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;\nSELECT user_seq.NEXTVAL FROM DUAL;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'GRANT',
                'description' => 'ユーザーやロールにデータベースの権限を付与するDCL文。',
                'sql_example' => "GRANT SELECT, INSERT ON users TO app_user;",
                'section' => 'DCL',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'REVOKE',
                'description' => 'ユーザーやロールから権限を取り消すDCL文。GRANTで付与した権限を削除する。',
                'sql_example' => "REVOKE INSERT ON users FROM app_user;",
                'section' => 'DCL',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NVL',
                'description' => 'NULLの場合に代替値を返すOracle固有の関数。NULL値を別の値に置き換えたい場合に使用する。',
                'sql_example' => "SELECT name, NVL(bonus, 0) AS bonus FROM employees;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DECODE',
                'description' => '条件に応じて異なる値を返すOracle固有の関数。CASEと似た動作をする。',
                'sql_example' => "SELECT name, DECODE(status, 'A', '有効', 'I', '無効', '不明') FROM users;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROWNUM',
                'description' => 'Oracleで結果セットの行番号を返す擬似列。上位N件を取得する際に使用する。',
                'sql_example' => "SELECT * FROM employees WHERE ROWNUM <= 10;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第1正規形',
                'description' => 'テーブルの各カラムが原子値（分割できない値）のみを持ち、繰り返しグループが存在しない状態。',
                'sql_example' => "-- NG: phone列に複数の値\n-- OK: 1行1値に分割する",
                'section' => '正規化',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第2正規形',
                'description' => '第1正規形を満たし、かつ非キー属性が主キーに完全関数従属している状態。部分関数従属を排除する。',
                'sql_example' => "-- 複合主キーの一部にしか依存しないカラムを別テーブルに分離する",
                'section' => '正規化',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第3正規形',
                'description' => '第2正規形を満たし、かつ非キー属性間の推移的関数従属が存在しない状態。',
                'sql_example' => "-- 非キー属性が別の非キー属性に依存している場合、別テーブルに分離する",
                'section' => '正規化',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
                        [
                'term' => 'CROSS JOIN',
                'description' => '2つのテーブルのすべての組み合わせを返す結合。直積とも呼ぶ。ON句は不要。',
                'sql_example' => "SELECT * FROM colors CROSS JOIN sizes;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SELF JOIN',
                'description' => '同じテーブルを自分自身と結合する手法。階層構造や上司・部下の関係を表現する際に使用する。',
                'sql_example' => "SELECT e.name, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;",
                'section' => 'JOIN',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NATURAL JOIN',
                'description' => '2つのテーブルで同じ名前のカラムを自動的に結合条件として使用するJOIN。ON句が不要。',
                'sql_example' => "SELECT * FROM employees NATURAL JOIN departments;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COALESCE',
                'description' => '引数のリストで最初のNULLでない値を返す関数。複数の列のNULL処理に便利。',
                'sql_example' => "SELECT COALESCE(phone, mobile, 'なし') FROM users;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NULLIF',
                'description' => '2つの値が等しい場合にNULLを返す関数。ゼロ除算を避けるために使用することが多い。',
                'sql_example' => "SELECT salary / NULLIF(hours, 0) FROM employees;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROUND',
                'description' => '数値を指定した桁数に四捨五入する関数。',
                'sql_example' => "SELECT ROUND(3.14159, 2) FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRUNC',
                'description' => '数値または日付を指定した桁数で切り捨てるOracle固有の関数。',
                'sql_example' => "SELECT TRUNC(3.14159, 2) FROM DUAL;\nSELECT TRUNC(SYSDATE) FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TO_CHAR',
                'description' => '数値や日付を文字列に変換するOracle固有の関数。書式を指定できる。',
                'sql_example' => "SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TO_DATE',
                'description' => '文字列を日付型に変換するOracle固有の関数。書式を指定する必要がある。',
                'sql_example' => "SELECT TO_DATE('2024/01/01', 'YYYY/MM/DD') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TO_NUMBER',
                'description' => '文字列を数値型に変換するOracle固有の関数。',
                'sql_example' => "SELECT TO_NUMBER('123.45') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UPPER',
                'description' => '文字列をすべて大文字に変換する関数。',
                'sql_example' => "SELECT UPPER('hello world') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LOWER',
                'description' => '文字列をすべて小文字に変換する関数。',
                'sql_example' => "SELECT LOWER('HELLO WORLD') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LENGTH',
                'description' => '文字列の文字数を返す関数。',
                'sql_example' => "SELECT LENGTH('Hello') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SUBSTR',
                'description' => '文字列の一部を取り出す関数。開始位置と取り出す文字数を指定する。',
                'sql_example' => "SELECT SUBSTR('Hello World', 1, 5) FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INSTR',
                'description' => '文字列の中で指定した文字列が最初に出現する位置を返すOracle固有の関数。',
                'sql_example' => "SELECT INSTR('Hello World', 'World') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CONCAT',
                'description' => '2つの文字列を連結する関数。||演算子でも同様の処理ができる。',
                'sql_example' => "SELECT CONCAT('Hello', ' World') FROM DUAL;\nSELECT 'Hello' || ' World' FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRIM',
                'description' => '文字列の前後の空白または指定した文字を除去する関数。',
                'sql_example' => "SELECT TRIM('  Hello  ') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'REPLACE',
                'description' => '文字列内の指定した文字列を別の文字列に置換する関数。',
                'sql_example' => "SELECT REPLACE('Hello World', 'World', 'SQL') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SYSDATE',
                'description' => '現在の日付と時刻を返すOracle固有の擬似列。',
                'sql_example' => "SELECT SYSDATE FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ADD_MONTHS',
                'description' => '日付に指定した月数を加算するOracle固有の関数。',
                'sql_example' => "SELECT ADD_MONTHS(SYSDATE, 3) FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MONTHS_BETWEEN',
                'description' => '2つの日付の間の月数を返すOracle固有の関数。',
                'sql_example' => "SELECT MONTHS_BETWEEN(SYSDATE, hire_date) FROM employees;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LAST_DAY',
                'description' => '指定した日付が含まれる月の最終日を返すOracle固有の関数。',
                'sql_example' => "SELECT LAST_DAY(SYSDATE) FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NEXT_DAY',
                'description' => '指定した日付以降で最初に来る指定した曜日の日付を返すOracle固有の関数。',
                'sql_example' => "SELECT NEXT_DAY(SYSDATE, '月曜日') FROM DUAL;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'RANK',
                'description' => '結果セット内の行に順位を付ける分析関数。同順位の場合は次の順位をスキップする。',
                'sql_example' => "SELECT name, salary, RANK() OVER (ORDER BY salary DESC) AS rank\nFROM employees;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DENSE_RANK',
                'description' => '結果セット内の行に順位を付ける分析関数。同順位の場合でも次の順位をスキップしない。',
                'sql_example' => "SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rank\nFROM employees;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROW_NUMBER',
                'description' => '結果セット内の各行に一意の連番を付ける分析関数。同じ値でも異なる番号が付く。',
                'sql_example' => "SELECT name, ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num\nFROM employees;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'WITH句（CTE）',
                'description' => 'Common Table Expression。複雑なクエリを一時的な名前付き結果セットとして定義できる構文。',
                'sql_example' => "WITH high_salary AS (\n  SELECT * FROM employees WHERE salary > 500000\n)\nSELECT * FROM high_salary WHERE department = '営業';",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'スカラーサブクエリ',
                'description' => 'SELECT句の中に記述するサブクエリ。必ず1行1列の値を返す必要がある。',
                'sql_example' => "SELECT name,\n  (SELECT department_name FROM departments WHERE id = e.dept_id) AS dept\nFROM employees e;",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'インラインビュー',
                'description' => 'FROM句の中にサブクエリを記述したもの。一時的なテーブルとして扱える。',
                'sql_example' => "SELECT * FROM\n  (SELECT name, salary FROM employees WHERE salary > 300000) high_earners\nWHERE salary > 500000;",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ALL',
                'description' => 'サブクエリが返すすべての値と比較する演算子。すべての値に対して条件が真の場合に結果を返す。',
                'sql_example' => "SELECT name FROM employees\nWHERE salary > ALL (SELECT salary FROM managers);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ANY',
                'description' => 'サブクエリが返すいずれかの値と比較する演算子。いずれかの値に対して条件が真の場合に結果を返す。',
                'sql_example' => "SELECT name FROM employees\nWHERE salary > ANY (SELECT salary FROM managers);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CONSTRAINT',
                'description' => 'テーブルに制約を定義するキーワード。PRIMARY KEY、FOREIGN KEY、UNIQUE、NOT NULL、CHECKなどの制約に名前を付けられる。',
                'sql_example' => "CREATE TABLE orders (\n  id INT,\n  amount INT,\n  CONSTRAINT pk_orders PRIMARY KEY (id),\n  CONSTRAINT chk_amount CHECK (amount > 0)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CHECK制約',
                'description' => 'カラムに入力できる値の範囲や条件を制限する制約。',
                'sql_example' => "CREATE TABLE employees (\n  id INT PRIMARY KEY,\n  age INT CHECK (age >= 18 AND age <= 65)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ON DELETE CASCADE',
                'description' => '親テーブルのレコードが削除された時に、関連する子テーブルのレコードも自動的に削除する外部キー制約のオプション。',
                'sql_example' => "CREATE TABLE orders (\n  id INT PRIMARY KEY,\n  user_id INT,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MATERIALIZED VIEW',
                'description' => 'クエリの結果を物理的に保存するビュー。通常のビューと異なり、実データを持つため参照が高速。',
                'sql_example' => "CREATE MATERIALIZED VIEW mv_sales AS\nSELECT department, SUM(sales) FROM orders GROUP BY department;",
                'section' => 'ビュー',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SYNONYM',
                'description' => 'テーブル・ビュー・シーケンスなどのオブジェクトに別名をつけるOracle固有のオブジェクト。',
                'sql_example' => "CREATE SYNONYM emp FOR hr.employees;\nSELECT * FROM emp;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'PROCEDURE',
                'description' => '一連のSQL文をまとめて名前を付けたデータベースオブジェクト。パラメータを受け取り処理を実行する。',
                'sql_example' => "CREATE PROCEDURE raise_salary(emp_id INT, amount INT)\nAS BEGIN\n  UPDATE employees SET salary = salary + amount WHERE id = emp_id;\nEND;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FUNCTION',
                'description' => '処理を実行して必ず値を返すデータベースオブジェクト。SELECT文の中で使用できる。',
                'sql_example' => "CREATE FUNCTION get_bonus(salary INT)\nRETURN INT\nAS BEGIN\n  RETURN salary * 0.1;\nEND;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRIGGER',
                'description' => 'テーブルへのINSERT・UPDATE・DELETE操作が行われた時に自動的に実行されるデータベースオブジェクト。',
                'sql_example' => "CREATE TRIGGER log_update\nAFTER UPDATE ON employees\nFOR EACH ROW\nBEGIN\n  INSERT INTO audit_log VALUES (OLD.id, NEW.salary, SYSDATE);\nEND;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LOCK TABLE',
                'description' => 'テーブルを明示的にロックするSQL文。他のユーザーからのアクセスを制御する。',
                'sql_example' => "LOCK TABLE employees IN EXCLUSIVE MODE;",
                'section' => 'トランザクション',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRUNCATE vs DELETE',
                'description' => 'TRUNCATEはDDL文でロールバック不可・高速。DELETEはDML文でロールバック可能・WHERE句で条件指定できる。',
                'sql_example' => "-- ロールバック可能\nDELETE FROM logs;\nROLLBACK;\n\n-- ロールバック不可\nTRUNCATE TABLE logs;",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CREATE INDEX',
                'description' => 'テーブルのカラムにインデックスを作成するDDL文。検索・結合・ソートのパフォーマンスが向上する。',
                'sql_example' => "CREATE INDEX idx_name ON employees(name);\nCREATE UNIQUE INDEX idx_email ON users(email);",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DROP INDEX',
                'description' => 'インデックスを削除するDDL文。',
                'sql_example' => "DROP INDEX idx_name;",
                'section' => 'DDL',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'RENAME',
                'description' => 'テーブルやオブジェクトの名前を変更するDDL文。',
                'sql_example' => "RENAME employees TO staff;",
                'section' => 'DDL',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COMMENT',
                'description' => 'テーブルやカラムにコメントを付与するDDL文。データ辞書に保存される。',
                'sql_example' => "COMMENT ON TABLE employees IS '従業員マスタ';\nCOMMENT ON COLUMN employees.salary IS '月給（円）';",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INSERT INTO SELECT',
                'description' => 'SELECT文の結果を別のテーブルに挿入するDML文。大量データのコピーに使用する。',
                'sql_example' => "INSERT INTO employees_backup\nSELECT * FROM employees WHERE hire_date < '2020-01-01';",
                'section' => 'DML',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MERGE',
                'description' => 'ソーステーブルのデータに基づいてターゲットテーブルのINSERT・UPDATE・DELETEを一括で行うDML文。UPSERT処理に使用する。',
                'sql_example' => "MERGE INTO target t\nUSING source s ON (t.id = s.id)\nWHEN MATCHED THEN UPDATE SET t.name = s.name\nWHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name);",
                'section' => 'DML',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FETCH',
                'description' => 'Oracle 12c以降で使用できる上位N件取得の構文。ROWNUMより直感的に書ける。',
                'sql_example' => "SELECT * FROM employees\nORDER BY salary DESC\nFETCH FIRST 10 ROWS ONLY;",
                'section' => 'SELECT',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'OFFSET',
                'description' => 'FETCH句と組み合わせて使用し、指定した行数をスキップして結果を取得する構文。ページネーションに使用する。',
                'sql_example' => "SELECT * FROM employees\nORDER BY id\nOFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;",
                'section' => 'SELECT',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'PIVOT',
                'description' => '行データを列に変換する演算子。集計結果をクロス集計表形式で表示する際に使用する。',
                'sql_example' => "SELECT * FROM sales\nPIVOT (SUM(amount) FOR quarter IN ('Q1','Q2','Q3','Q4'));",
                'section' => '集計',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROLLUP',
                'description' => 'GROUP BYの拡張で、指定したカラムの小計・合計を自動的に追加する演算子。',
                'sql_example' => "SELECT department, job, SUM(salary)\nFROM employees\nGROUP BY ROLLUP(department, job);",
                'section' => '集計',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CUBE',
                'description' => 'GROUP BYの拡張で、指定したカラムのすべての組み合わせの小計・合計を自動的に追加する演算子。',
                'sql_example' => "SELECT department, job, SUM(salary)\nFROM employees\nGROUP BY CUBE(department, job);",
                'section' => '集計',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'GROUPING SETS',
                'description' => 'GROUP BYの拡張で、複数のグループ化の組み合わせを指定できる演算子。ROLLUPやCUBEより細かく制御できる。',
                'sql_example' => "SELECT department, job, SUM(salary)\nFROM employees\nGROUP BY GROUPING SETS((department),(job),(department,job));",
                'section' => '集計',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データ型：VARCHAR2',
                'description' => 'Oracle固有の可変長文字列型。最大4000バイト。使用した分だけ領域を使用するため効率的。',
                'sql_example' => "CREATE TABLE users (\n  name VARCHAR2(100)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データ型：NUMBER',
                'description' => 'Oracle固有の数値型。精度と小数点以下の桁数を指定できる。NUMBER(p,s)で使用する。',
                'sql_example' => "CREATE TABLE products (\n  price NUMBER(10, 2)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データ型：DATE',
                'description' => 'Oracleの日付型。年月日時分秒を格納できる。日付と時刻の両方を持つ点がANSI標準と異なる。',
                'sql_example' => "CREATE TABLE events (\n  event_date DATE\n);\nSELECT TO_CHAR(event_date, 'YYYY/MM/DD HH24:MI:SS') FROM events;",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データ型：CLOB',
                'description' => '大量のテキストデータを格納するOracle固有のデータ型。最大4GBまで格納できる。',
                'sql_example' => "CREATE TABLE articles (\n  content CLOB\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データ型：BLOB',
                'description' => '画像や動画などのバイナリデータを格納するOracle固有のデータ型。最大4GBまで格納できる。',
                'sql_example' => "CREATE TABLE files (\n  file_data BLOB\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DUAL',
                'description' => 'Oracleが提供する特殊な1行1列のダミーテーブル。関数の動作確認や定数の取得に使用する。',
                'sql_example' => "SELECT SYSDATE FROM DUAL;\nSELECT 1 + 1 FROM DUAL;",
                'section' => 'オブジェクト',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'データディクショナリ',
                'description' => 'データベースの構造情報（テーブル・カラム・制約など）を管理するOracle固有のシステムテーブル群。USER_TABLES、ALL_COLUMNSなどがある。',
                'sql_example' => "SELECT table_name FROM USER_TABLES;\nSELECT column_name, data_type FROM USER_TAB_COLUMNS WHERE table_name = 'EMPLOYEES';",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FLASHBACK',
                'description' => '過去の特定時点のデータを参照・復元するOracle固有の機能。誤って削除・更新したデータの復元に使用する。',
                'sql_example' => "SELECT * FROM employees AS OF TIMESTAMP (SYSTIMESTAMP - INTERVAL '1' HOUR);",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
        ];

        foreach ($words as $word) {
            Word::firstOrCreate(['term' => $word['term']], $word);
        }
    }
}