<?php

namespace Database\Seeders;

use App\Models\Word;
use Illuminate\Database\Seeder;

class WordSeeder extends Seeder
{
    public function run(): void
    {
        $words = [
            [
                'term' => 'SELECT',
                'description' => 'テーブルからデータを取得するSQL文。取得するカラムを指定する。',
                'sql_example' => "SELECT id, name, email FROM users;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'WHERE',
                'description' => '条件を指定してデータを絞り込む句。',
                'sql_example' => "SELECT * FROM users WHERE age >= 20;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ORDER BY',
                'description' => '取得結果を指定したカラムで並び替える句。ASC（昇順）またはDESC（降順）を指定できる。',
                'sql_example' => "SELECT * FROM users ORDER BY created_at DESC;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'GROUP BY',
                'description' => '指定したカラムの値でグループ化する句。集計関数と組み合わせて使う。',
                'sql_example' => "SELECT department, COUNT(*) FROM employees GROUP BY department;",
                'section' => '集計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'HAVING',
                'description' => 'GROUP BYでグループ化した結果にさらに条件を指定する句。WHEREと違い集計関数が使える。',
                'sql_example' => "SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) >= 5;",
                'section' => '集計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INNER JOIN',
                'description' => '2つのテーブルで一致するデータだけを結合して取得するJOIN。ON句で結合条件を指定する。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nINNER JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LEFT JOIN',
                'description' => '左テーブルのすべてのレコードと、右テーブルで一致するレコードを結合する。右テーブルに一致がない場合はNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nLEFT JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DISTINCT',
                'description' => '重複する行を除いてデータを取得するキーワード。',
                'sql_example' => "SELECT DISTINCT department FROM employees;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COUNT',
                'description' => '行数を数える集計関数。COUNT(*)は全行数、COUNT(カラム名)はNULL以外の行数を返す。',
                'sql_example' => "SELECT COUNT(*) FROM users;\nSELECT COUNT(email) FROM users;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SUM',
                'description' => '指定したカラムの合計値を返す集計関数。',
                'sql_example' => "SELECT SUM(price) FROM orders;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'AVG',
                'description' => '指定したカラムの平均値を返す集計関数。',
                'sql_example' => "SELECT AVG(salary) FROM employees;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MAX',
                'description' => '指定したカラムの最大値を返す集計関数。',
                'sql_example' => "SELECT MAX(price) FROM products;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MIN',
                'description' => '指定したカラムの最小値を返す集計関数。',
                'sql_example' => "SELECT MIN(price) FROM products;",
                'section' => '集計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SUBQUERY',
                'description' => 'SELECT文の中に別のSELECT文を入れ子にしたもの。サブクエリとも呼ぶ。',
                'sql_example' => "SELECT name FROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'EXISTS',
                'description' => 'サブクエリが1件以上の結果を返す場合にTRUEとなる演算子。',
                'sql_example' => "SELECT name FROM customers c\nWHERE EXISTS (\n  SELECT 1 FROM orders o WHERE o.customer_id = c.id\n);",
                'section' => 'サブクエリ',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'IN',
                'description' => '指定したリストの中にカラムの値が含まれるかどうかを判定する演算子。',
                'sql_example' => "SELECT * FROM products WHERE category IN ('食品', '飲料', '日用品');",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'LIKE',
                'description' => '文字列のパターンマッチングを行う演算子。%は任意の文字列、_は任意の1文字を表す。',
                'sql_example' => "SELECT * FROM users WHERE name LIKE '田%';",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NULL',
                'description' => '値が存在しないことを表す特殊な値。IS NULLまたはIS NOT NULLで判定する。=演算子では比較できない。',
                'sql_example' => "SELECT * FROM users WHERE email IS NULL;",
                'section' => 'SELECT',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CASE',
                'description' => '条件によって異なる値を返す式。プログラミングのif文に相当する。',
                'sql_example' => "SELECT name,\n  CASE\n    WHEN score >= 80 THEN '優'\n    WHEN score >= 60 THEN '良'\n    ELSE '可'\n  END AS grade\nFROM students;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'PRIMARY KEY',
                'description' => 'テーブルの各行を一意に識別するための制約。NULL不可かつ重複不可。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  name VARCHAR(100)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FOREIGN KEY',
                'description' => '他のテーブルの主キーを参照する制約。参照整合性を保つために使用する。',
                'sql_example' => "CREATE TABLE orders (\n  id INT PRIMARY KEY,\n  user_id INT,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNIQUE',
                'description' => 'カラムの値が重複しないことを保証する制約。NULLは複数許容される場合がある。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  email VARCHAR(255) UNIQUE\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NOT NULL',
                'description' => 'カラムにNULL値を許可しない制約。必ず値が入力される必要がある。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DEFAULT',
                'description' => 'カラムに値が指定されなかった場合に自動的に設定される値を定義する制約。',
                'sql_example' => "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  status VARCHAR(20) DEFAULT 'active'\n);",
                'section' => 'テーブル設計',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INDEX',
                'description' => 'データの検索速度を向上させるためのデータ構造。検索・結合・ソートのパフォーマンスが改善される。',
                'sql_example' => "CREATE INDEX idx_users_email ON users(email);",
                'section' => 'テーブル設計',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'RIGHT JOIN',
                'description' => '右テーブルのすべてのレコードと、左テーブルで一致するレコードを結合する。左テーブルに一致がない場合はNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nRIGHT JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'FULL OUTER JOIN',
                'description' => '左右両方のテーブルのすべてのレコードを結合する。一致しないレコードはNULLになる。',
                'sql_example' => "SELECT e.name, d.department_name\nFROM employees e\nFULL OUTER JOIN departments d ON e.department_id = d.id;",
                'section' => 'JOIN',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNION',
                'description' => '2つのSELECT文の結果を縦に結合する演算子。重複行は自動的に除去される。',
                'sql_example' => "SELECT name FROM employees\nUNION\nSELECT name FROM contractors;",
                'section' => '集合演算',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UNION ALL',
                'description' => '2つのSELECT文の結果を縦に結合する演算子。UNIONと違い重複行も含めてすべて返す。',
                'sql_example' => "SELECT name FROM employees\nUNION ALL\nSELECT name FROM contractors;",
                'section' => '集合演算',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INTERSECT',
                'description' => '2つのSELECT文の結果の共通部分を返す演算子。',
                'sql_example' => "SELECT name FROM employees\nINTERSECT\nSELECT name FROM managers;",
                'section' => '集合演算',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'MINUS',
                'description' => '1つ目のSELECT文の結果から2つ目の結果を除いた差集合を返す演算子。',
                'sql_example' => "SELECT name FROM employees\nMINUS\nSELECT name FROM managers;",
                'section' => '集合演算',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'BETWEEN',
                'description' => '指定した範囲内の値を検索する演算子。境界値も含まれる。',
                'sql_example' => "SELECT * FROM products WHERE price BETWEEN 1000 AND 5000;",
                'section' => 'SELECT',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'TRUNCATE',
                'description' => 'テーブルの全データを削除するDDL文。DELETEと違いロールバックできない場合がある。',
                'sql_example' => "TRUNCATE TABLE logs;",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'INSERT',
                'description' => 'テーブルに新しいレコードを追加するDML文。',
                'sql_example' => "INSERT INTO users (name, email) VALUES ('田中', 'tanaka@example.com');",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'UPDATE',
                'description' => 'テーブルの既存レコードを更新するDML文。WHEREで条件を指定しないと全件更新される。',
                'sql_example' => "UPDATE users SET status = 'inactive' WHERE last_login < '2024-01-01';",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DELETE',
                'description' => 'テーブルからレコードを削除するDML文。WHEREで条件を指定しないと全件削除される。',
                'sql_example' => "DELETE FROM users WHERE status = 'inactive';",
                'section' => 'DML',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'CREATE TABLE',
                'description' => '新しいテーブルを作成するDDL文。カラム名・データ型・制約を定義する。',
                'sql_example' => "CREATE TABLE products (\n  id INT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL,\n  price INT DEFAULT 0\n);",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ALTER TABLE',
                'description' => '既存テーブルの構造を変更するDDL文。カラムの追加・削除・変更などができる。',
                'sql_example' => "ALTER TABLE users ADD COLUMN phone VARCHAR(20);\nALTER TABLE users DROP COLUMN phone;",
                'section' => 'DDL',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DROP TABLE',
                'description' => 'テーブルを完全に削除するDDL文。テーブル構造とデータがすべて削除される。',
                'sql_example' => "DROP TABLE temp_logs;",
                'section' => 'DDL',
                'difficulty' => 'easy',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'COMMIT',
                'description' => 'トランザクション内の変更を確定させるTCL文。COMMITするまで変更は他のセッションから見えない。',
                'sql_example' => "BEGIN;\nUPDATE accounts SET balance = balance - 1000 WHERE id = 1;\nUPDATE accounts SET balance = balance + 1000 WHERE id = 2;\nCOMMIT;",
                'section' => 'トランザクション',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROLLBACK',
                'description' => 'トランザクション内の変更を取り消すTCL文。エラー発生時に変更をなかったことにする。',
                'sql_example' => "BEGIN;\nUPDATE accounts SET balance = balance - 1000 WHERE id = 1;\nROLLBACK;",
                'section' => 'トランザクション',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SAVEPOINT',
                'description' => 'トランザクション内に中間ポイントを設定するTCL文。SAVEPOINTまで部分的にROLLBACKできる。',
                'sql_example' => "SAVEPOINT sp1;\nUPDATE users SET status = 'vip' WHERE id = 1;\nROLLBACK TO sp1;",
                'section' => 'トランザクション',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'VIEW',
                'description' => 'SELECT文を仮想テーブルとして保存したもの。複雑なクエリを簡略化したり、アクセス制御に使用する。',
                'sql_example' => "CREATE VIEW active_users AS\nSELECT id, name, email FROM users WHERE status = 'active';",
                'section' => 'ビュー',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'SEQUENCE',
                'description' => '連続した数値を自動生成するオブジェクト。主キーの自動採番に使用される。',
                'sql_example' => "CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;\nSELECT user_seq.NEXTVAL FROM DUAL;",
                'section' => 'オブジェクト',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'GRANT',
                'description' => 'ユーザーやロールにデータベースの権限を付与するDCL文。',
                'sql_example' => "GRANT SELECT, INSERT ON users TO app_user;",
                'section' => 'DCL',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'REVOKE',
                'description' => 'ユーザーやロールから権限を取り消すDCL文。GRANTで付与した権限を削除する。',
                'sql_example' => "REVOKE INSERT ON users FROM app_user;",
                'section' => 'DCL',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'NVL',
                'description' => 'NULLの場合に代替値を返すOracle固有の関数。NULL値を別の値に置き換えたい場合に使用する。',
                'sql_example' => "SELECT name, NVL(bonus, 0) AS bonus FROM employees;",
                'section' => '関数',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'DECODE',
                'description' => '条件に応じて異なる値を返すOracle固有の関数。CASEと似た動作をする。',
                'sql_example' => "SELECT name, DECODE(status, 'A', '有効', 'I', '無効', '不明') FROM users;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => 'ROWNUM',
                'description' => 'Oracleで結果セットの行番号を返す擬似列。上位N件を取得する際に使用する。',
                'sql_example' => "SELECT * FROM employees WHERE ROWNUM <= 10;",
                'section' => '関数',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第1正規形',
                'description' => 'テーブルの各カラムが原子値（分割できない値）のみを持ち、繰り返しグループが存在しない状態。',
                'sql_example' => "-- NG: phone列に複数の値\n-- OK: 1行1値に分割する",
                'section' => '正規化',
                'difficulty' => 'normal',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第2正規形',
                'description' => '第1正規形を満たし、かつ非キー属性が主キーに完全関数従属している状態。部分関数従属を排除する。',
                'sql_example' => "-- 複合主キーの一部にしか依存しないカラムを別テーブルに分離する",
                'section' => '正規化',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
            [
                'term' => '第3正規形',
                'description' => '第2正規形を満たし、かつ非キー属性間の推移的関数従属が存在しない状態。',
                'sql_example' => "-- 非キー属性が別の非キー属性に依存している場合、別テーブルに分離する",
                'section' => '正規化',
                'difficulty' => 'hard',
                'quiz_type' => 'choice',
            ],
        ];

        foreach ($words as $word) {
            Word::firstOrCreate(['term' => $word['term']], $word);
        }
    }
}